# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  blog.ricksmotorsportelectrics.com:
    site_hosts:
      - blog.ricksmotorsportelectrics.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:digimix/rickswp.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
    env:      
	  disable_wp_cron: false
      wp_home: http://blog.ricksmotorsportelectrics.com
      wp_siteurl: http://blog.ricksmotorsportelectrics.com/wp
      wp_env: production
      db_name: rmetips001_prod
      db_user: rmetips001_dbuser
    db_import: ../site/ricks_dev.sql #(option to import .sql on 'vagrant up') 
